# ===-------------------------------------------------------------=== #
#    Copyright © 2024, Geomatys, SAS. All rights reserved.
#    http://www.geomatys.com
#
#    Licensed under the Apache License, Version 2.0
#    (the "License"); you may not use this file except in
#    compliance with the License. You may obtain a copy of the
#    License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing,
#    software distributed under the License is distributed on an
#    "AS IS" BASIS,WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
#    either express or implied. See the License for the specific
#    language governing permissions and limitations under the
#    License.
# ===-------------------------------------------------------------=== #

"""This is the iso_639_2 module.

This module contains a dictionary of language codes derived from
international standard ISO 639-2. The `metadata` contains metadta
converning the source of the data, while the `data` element contains
a tuple of the actual codes.

When a choice in the source was given between a bibliographic or terminology
three-letter designator, the terminology option was chosen.
"""

from __future__ import annotations

from enum import Enum

__metadata__ = {
    "source_url": "https://www.loc.gov/standards/iso639-2/php/"
    "code_list.php",

    "source_accessed_date_time": "2024-08-14T14:34:12.949787+00:00",

    "source_last_updated": "2017-12-21T00:00:00",

    "source_organization": "Library of Congress, United States of America",

    "source_country_alpha_3": "usa",

    "source_language": "eng",

    "source_encoding": "ISO-8859-1",

    "source_title": "ISO 639-2 Language Code List - Codes for the "
    "representation of names of languages (Library of Congress)",

    "source_description": "This document contains the ISO 639-2 Alpha-3 "
    "codes for the representation of names of languages.",

    "source_keywords": "ISO 639-2,language codes,alpha-3 codes,alpha-2"
    " codes,bibliographic codes,terminology codes"
}


class IsoLanguageCodes(Enum):
    """
    A list of three-letter codes for languages as defined in
    international standard ISO 639-2.
    """
    AAR = "aar"
    ABK = "abk"
    ACE = "ace"
    ACH = "ach"
    ADA = "ada"
    ADY = "ady"
    AFA = "afa"
    AFH = "afh"
    AFR = "afr"
    AIN = "ain"
    AKA = "aka"
    AKK = "akk"
    ALE = "ale"
    ALG = "alg"
    ALT = "alt"
    AMH = "amh"
    ANG = "ang"
    ANP = "anp"
    APA = "apa"
    ARA = "ara"
    ARC = "arc"
    ARG = "arg"
    ARN = "arn"
    ARP = "arp"
    ART = "art"
    ARW = "arw"
    ASM = "asm"
    AST = "ast"
    ATH = "ath"
    AUS = "aus"
    AVA = "ava"
    AVE = "ave"
    AWA = "awa"
    AYM = "aym"
    AZE = "aze"
    BAD = "bad"
    BAI = "bai"
    BAK = "bak"
    BAL = "bal"
    BAM = "bam"
    BAN = "ban"
    BAS = "bas"
    BAT = "bat"
    BEJ = "bej"
    BEL = "bel"
    BEM = "bem"
    BEN = "ben"
    BER = "ber"
    BHO = "bho"
    BIH = "bih"
    BIK = "bik"
    BIN = "bin"
    BIS = "bis"
    BLA = "bla"
    BNT = "bnt"
    BOD = "bod"
    BOS = "bos"
    BRA = "bra"
    BRE = "bre"
    BTK = "btk"
    BUA = "bua"
    BUG = "bug"
    BUL = "bul"
    BYN = "byn"
    CAD = "cad"
    CAI = "cai"
    CAR = "car"
    CAT = "cat"
    CAU = "cau"
    CEB = "ceb"
    CEL = "cel"
    CES = "ces"
    CHA = "cha"
    CHB = "chb"
    CHE = "che"
    CHG = "chg"
    CHK = "chk"
    CHM = "chm"
    CHN = "chn"
    CHO = "cho"
    CHP = "chp"
    CHR = "chr"
    CHU = "chu"
    COS = "cos"
    CPE = "cpe"
    CPF = "cpf"
    CPP = "cpp"
    CRE = "cre"
    CRH = "crh"
    CRP = "crp"
    CSB = "csb"
    CUS = "cus"
    CYM = "cym"
    DAK = "dak"
    DAN = "dan"
    DAR = "dar"
    DAY = "day"
    DEL = "del"
    DEN = "den"
    DEU = "deu"
    DGR = "dgr"
    DIN = "din"
    DIV = "div"
    DOI = "doi"
    DRA = "dra"
    DSB = "dsb"
    DUA = "dua"
    DUM = "dum"
    DYU = "dyu"
    DZO = "dzo"
    EFI = "efi"
    EGY = "egy"
    EKA = "eka"
    ELL = "ell"
    ELX = "elx"
    ENG = "eng"
    ENM = "enm"
    EPO = "epo"
    EST = "est"
    EUS = "eus"
    EWE = "ewe"
    EWO = "ewo"
    FAN = "fan"
    FAO = "fao"
    FAS = "fas"
    FAT = "fat"
    FIJ = "fij"
    FIL = "fil"
    FIN = "fin"
    FIU = "fiu"
    FON = "fon"
    FRA = "fra"
    FRM = "frm"
    FRO = "fro"
    FRR = "frr"
    FRS = "frs"
    FRY = "fry"
    FUL = "ful"
    FUR = "fur"
    GAA = "gaa"
    GAY = "gay"
    GBA = "gba"
    GEM = "gem"
    GEZ = "gez"
    GIL = "gil"
    GLA = "gla"
    GLE = "gle"
    GLG = "glg"
    GLV = "glv"
    GMH = "gmh"
    GOH = "goh"
    GON = "gon"
    GOR = "gor"
    GOT = "got"
    GRB = "grb"
    GRC = "grc"
    GRN = "grn"
    GSW = "gsw"
    GUJ = "guj"
    GWI = "gwi"
    HAI = "hai"
    HAT = "hat"
    HAU = "hau"
    HAW = "haw"
    HEB = "heb"
    HER = "her"
    HIL = "hil"
    HIM = "him"
    HIN = "hin"
    HIT = "hit"
    HMN = "hmn"
    HMO = "hmo"
    HRV = "hrv"
    HSB = "hsb"
    HUN = "hun"
    HUP = "hup"
    HYE = "hye"
    IBA = "iba"
    IBO = "ibo"
    IDO = "ido"
    III = "iii"
    IJO = "ijo"
    IKU = "iku"
    ILE = "ile"
    ILO = "ilo"
    INA = "ina"
    INC = "inc"
    IND = "ind"
    INE = "ine"
    INH = "inh"
    IPK = "ipk"
    IRA = "ira"
    IRO = "iro"
    ISL = "isl"
    ITA = "ita"
    JAV = "jav"
    JBO = "jbo"
    JPN = "jpn"
    JPR = "jpr"
    JRB = "jrb"
    KAA = "kaa"
    KAB = "kab"
    KAC = "kac"
    KAL = "kal"
    KAM = "kam"
    KAN = "kan"
    KAR = "kar"
    KAS = "kas"
    KAT = "kat"
    KAU = "kau"
    KAW = "kaw"
    KAZ = "kaz"
    KBD = "kbd"
    KHA = "kha"
    KHI = "khi"
    KHM = "khm"
    KHO = "kho"
    KIK = "kik"
    KIN = "kin"
    KIR = "kir"
    KMB = "kmb"
    KOK = "kok"
    KOM = "kom"
    KON = "kon"
    KOR = "kor"
    KOS = "kos"
    KPE = "kpe"
    KRC = "krc"
    KRL = "krl"
    KRO = "kro"
    KRU = "kru"
    KUA = "kua"
    KUM = "kum"
    KUR = "kur"
    KUT = "kut"
    LAD = "lad"
    LAH = "lah"
    LAM = "lam"
    LAO = "lao"
    LAT = "lat"
    LAV = "lav"
    LEZ = "lez"
    LIM = "lim"
    LIN = "lin"
    LIT = "lit"
    LOL = "lol"
    LOZ = "loz"
    LTZ = "ltz"
    LUA = "lua"
    LUB = "lub"
    LUG = "lug"
    LUI = "lui"
    LUN = "lun"
    LUO = "luo"
    LUS = "lus"
    MAD = "mad"
    MAG = "mag"
    MAH = "mah"
    MAI = "mai"
    MAK = "mak"
    MAL = "mal"
    MAN = "man"
    MAP = "map"
    MAR = "mar"
    MAS = "mas"
    MDF = "mdf"
    MDR = "mdr"
    MEN = "men"
    MGA = "mga"
    MIC = "mic"
    MIN = "min"
    MIS = "mis"
    MKD = "mkd"
    MKH = "mkh"
    MLG = "mlg"
    MLT = "mlt"
    MNC = "mnc"
    MNI = "mni"
    MNO = "mno"
    MOH = "moh"
    MON = "mon"
    MOS = "mos"
    MRI = "mri"
    MSA = "msa"
    MUL = "mul"
    MUN = "mun"
    MUS = "mus"
    MWL = "mwl"
    MWR = "mwr"
    MYA = "mya"
    MYN = "myn"
    MYV = "myv"
    NAH = "nah"
    NAI = "nai"
    NAP = "nap"
    NAU = "nau"
    NAV = "nav"
    NBL = "nbl"
    NDE = "nde"
    NDO = "ndo"
    NDS = "nds"
    NEP = "nep"
    NEW = "new"
    NIA = "nia"
    NIC = "nic"
    NIU = "niu"
    NLD = "nld"
    NNO = "nno"
    NOB = "nob"
    NOG = "nog"
    NON = "non"
    NOR = "nor"
    NQO = "nqo"
    NSO = "nso"
    NUB = "nub"
    NWC = "nwc"
    NYA = "nya"
    NYM = "nym"
    NYN = "nyn"
    NYO = "nyo"
    NZI = "nzi"
    OCI = "oci"
    OJI = "oji"
    ORI = "ori"
    ORM = "orm"
    OSA = "osa"
    OSS = "oss"
    OTA = "ota"
    OTO = "oto"
    PAA = "paa"
    PAG = "pag"
    PAL = "pal"
    PAM = "pam"
    PAN = "pan"
    PAP = "pap"
    PAU = "pau"
    PEO = "peo"
    PHI = "phi"
    PHN = "phn"
    PLI = "pli"
    POL = "pol"
    PON = "pon"
    POR = "por"
    PRA = "pra"
    PRO = "pro"
    PUS = "pus"
    QUE = "que"
    RAJ = "raj"
    RAP = "rap"
    RAR = "rar"
    ROA = "roa"
    ROH = "roh"
    ROM = "rom"
    RON = "ron"
    RUN = "run"
    RUP = "rup"
    RUS = "rus"
    SAD = "sad"
    SAG = "sag"
    SAH = "sah"
    SAI = "sai"
    SAL = "sal"
    SAM = "sam"
    SAN = "san"
    SAS = "sas"
    SAT = "sat"
    SCN = "scn"
    SCO = "sco"
    SEL = "sel"
    SEM = "sem"
    SGA = "sga"
    SGN = "sgn"
    SHN = "shn"
    SID = "sid"
    SIN = "sin"
    SIO = "sio"
    SIT = "sit"
    SLA = "sla"
    SLK = "slk"
    SLV = "slv"
    SMA = "sma"
    SME = "sme"
    SMI = "smi"
    SMJ = "smj"
    SMN = "smn"
    SMO = "smo"
    SMS = "sms"
    SNA = "sna"
    SND = "snd"
    SNK = "snk"
    SOG = "sog"
    SOM = "som"
    SON = "son"
    SOT = "sot"
    SPA = "spa"
    SQI = "sqi"
    SRD = "srd"
    SRN = "srn"
    SRP = "srp"
    SRR = "srr"
    SSA = "ssa"
    SSW = "ssw"
    SUK = "suk"
    SUN = "sun"
    SUS = "sus"
    SUX = "sux"
    SWA = "swa"
    SWE = "swe"
    SYC = "syc"
    SYR = "syr"
    TAH = "tah"
    TAI = "tai"
    TAM = "tam"
    TAT = "tat"
    TEL = "tel"
    TEM = "tem"
    TER = "ter"
    TET = "tet"
    TGK = "tgk"
    TGL = "tgl"
    THA = "tha"
    TIG = "tig"
    TIR = "tir"
    TIV = "tiv"
    TKL = "tkl"
    TLH = "tlh"
    TLI = "tli"
    TMH = "tmh"
    TOG = "tog"
    TON = "ton"
    TPI = "tpi"
    TSI = "tsi"
    TSN = "tsn"
    TSO = "tso"
    TUK = "tuk"
    TUM = "tum"
    TUP = "tup"
    TUR = "tur"
    TUT = "tut"
    TVL = "tvl"
    TWI = "twi"
    TYV = "tyv"
    UDM = "udm"
    UGA = "uga"
    UIG = "uig"
    UKR = "ukr"
    UMB = "umb"
    UND = "und"
    URD = "urd"
    UZB = "uzb"
    VAI = "vai"
    VEN = "ven"
    VIE = "vie"
    VOL = "vol"
    VOT = "vot"
    WAK = "wak"
    WAL = "wal"
    WAR = "war"
    WAS = "was"
    WEN = "wen"
    WLN = "wln"
    WOL = "wol"
    XAL = "xal"
    XHO = "xho"
    YAO = "yao"
    YAP = "yap"
    YID = "yid"
    YOR = "yor"
    YPK = "ypk"
    ZAP = "zap"
    ZBL = "zbl"
    ZEN = "zen"
    ZGH = "zgh"
    ZHA = "zha"
    ZHO = "zho"
    ZND = "znd"
    ZUL = "zul"
    ZUN = "zun"
    ZXX = "zxx"
    ZZA = "zza"
